-- Create entities described by logical diagram
-- Establish data types and default values
-- Establish Primary Keys for each entity
-- Record 'Created_Date' and 'Modified_Date' 
CREATE TABLE MODEL_YEAR
(Model_Year_ID INT AUTO_INCREMENT,
Model_Year INT,
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_MODEL_YEAR PRIMARY KEY (Model_Year_ID));

CREATE TABLE MAKE
(Make_ID INT AUTO_INCREMENT,
Make VARCHAR(50),
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_MAKE PRIMARY KEY (Make_ID));

CREATE TABLE MODEL
(Model_ID INT AUTO_INCREMENT,
Model VARCHAR(50),
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_MODEL PRIMARY KEY (Model_ID));

CREATE TABLE TRIM_TYPE
(Trim_Type_ID INT AUTO_INCREMENT,
Trim_Type VARCHAR(50),
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_TRIM_TYPE PRIMARY KEY (Trim_Type_ID));

CREATE TABLE BODY
(Body_ID INT AUTO_INCREMENT,
Body VARCHAR(50),
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_BODY PRIMARY KEY (Body_ID));

CREATE TABLE TRANSMISSION
(Transmission_ID INT AUTO_INCREMENT,
Transmission VARCHAR(50),
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_TRANSMISSION PRIMARY KEY (Transmission_ID));

CREATE TABLE STATE
(State_ID INT AUTO_INCREMENT,
State VARCHAR(2),
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_STATE PRIMARY KEY (State_ID));

CREATE TABLE COLOR
(Color_ID INT AUTO_INCREMENT,
Color VARCHAR(50),
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_COLOR PRIMARY KEY (Color_ID));

CREATE TABLE SELLER
(Seller_ID INT AUTO_INCREMENT,
Seller VARCHAR(50) DEFAULT 'Unknown',
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_SELLER PRIMARY KEY (Seller_ID));

CREATE TABLE CAR_SALE
(Sale_ID INT AUTO_INCREMENT,
VIN VARCHAR(50) NOT NULL,
Car_Condition VARCHAR(50),
Odometer INT,
MMR INT,
Selling_Price INT,
Sale_Date TIMESTAMP,
Model_Year_ID INT,
Make_ID INT, 
Model_ID INT, 
Trim_Type_ID INT,
Body_ID INT,
Transmission_ID INT,
State_ID INT,
Color_ID INT, 
Interior_Color_ID INT,
Seller_ID INT NOT NULL,
Created_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
Modified_Date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_SALE PRIMARY KEY (Sale_ID));

-- Establish primary keys of all entities as foreign keys for CAR_SALE
ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Model_Year_ID FOREIGN KEY (Model_Year_ID)
REFERENCES MODEL_YEAR(Model_Year_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Make_ID FOREIGN KEY (Make_ID)
REFERENCES MAKE(Make_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Model_ID FOREIGN KEY (Model_ID)
REFERENCES MODEL(Model_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Trim_Type_ID FOREIGN KEY (Trim_Type_ID)
REFERENCES TRIM_TYPE(Trim_Type_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Body_ID FOREIGN KEY (Body_ID)
REFERENCES BODY(Body_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Transmission_ID FOREIGN KEY (Transmission_ID)
REFERENCES TRANSMISSION(Transmission_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_State_ID FOREIGN KEY (State_ID)
REFERENCES STATE(State_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Color_ID FOREIGN KEY (Color_ID)
REFERENCES COLOR(Color_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Interior_Color_ID FOREIGN KEY (Interior_Color_ID)
REFERENCES COLOR(Color_ID);

ALTER TABLE CAR_SALE
ADD CONSTRAINT FK_CAR_SALE_Seller_ID FOREIGN KEY (Seller_ID)
REFERENCES SELLER(Seller_ID);
